# Generated by Django 5.2.9 on 2026-01-13 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_role'),
        ('requests_unified', '0002_degree_alter_request_assigned_staff_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='degree',
            field=models.ForeignKey(blank=True, help_text='The degree program the student is enrolled in.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='requests_unified.degree'),
        ),
    ]
