# Generated by Django 6.0.1 on 2026-01-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentrequest',
            old_name='created_at',
            new_name='submitted_at',
        ),
        migrations.AddField(
            model_name='studentrequest',
            name='course_name',
            field=models.CharField(default='Intro to Computer Science', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attachment',
            name='filename',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='request_type',
            field=models.CharField(max_length=100),
        ),
    ]
