# Generated by Django 6.0.1 on 2026-01-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_rename_created_at_studentrequest_submitted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='attachments/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
