# Generated by Django 5.2.9 on 2026-01-13 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_unified', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='request',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'secretary'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_assigned_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lecturers', models.ManyToManyField(blank=True, help_text='Lecturers who teach this course', limit_choices_to={'role': 'lecturer'}, related_name='taught_courses', to=settings.AUTH_USER_MODEL)),
                ('degrees', models.ManyToManyField(help_text='Degree programs that include this course', related_name='courses', to='requests_unified.degree')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='request',
            name='course',
            field=models.ForeignKey(blank=True, help_text='The course this request is related to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='requests_unified.course'),
        ),
    ]
